"""add_supplier_bank_fields

Revision ID: 4d7509381474
Revises: c1e4f6a8b0d2
Create Date: 2026-09-17 19:23:41.785152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d7509381474'
down_revision: Union[str, None] = 'c1e4f6a8b0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('bank_name', sa.String(length=128), nullable=True, comment='开户行名称'))
    op.add_column('suppliers', sa.Column('bank_account_no', sa.String(length=64), nullable=True, comment='银行账号'))
    op.add_column('suppliers', sa.Column('bank_account_name', sa.String(length=256), nullable=True, comment='银行账户名（对方户名）'))
    op.add_column('suppliers', sa.Column('tax_invoice_count', sa.Integer(), server_default='0', nullable=True, comment='关联进项发票数（缓存）'))
    op.create_index(op.f('ix_suppliers_bank_account_no'), 'suppliers', ['bank_account_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_bank_account_no'), table_name='suppliers')
    op.drop_column('suppliers', 'tax_invoice_count')
    op.drop_column('suppliers', 'bank_account_name')
    op.drop_column('suppliers', 'bank_account_no')
    op.drop_column('suppliers', 'bank_name')
    # ### end Alembic commands ###
