"""phase0 initial schema

Revision ID: c65913dc8d5b
Revises: 
Create Date: 2026-09-01 17:02:16.120391
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c65913dc8d5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aftersales_orders',
    sa.Column('aftersale_no', sa.String(length=128), nullable=False),
    sa.Column('order_no', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at_src', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aftersale_no')
    )
    op.create_index(op.f('ix_aftersales_orders_order_no'), 'aftersales_orders', ['order_no'], unique=False)
    op.create_index(op.f('ix_aftersales_orders_status'), 'aftersales_orders', ['status'], unique=False)
    op.create_table('allocated_expenses',
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('expense_type', sa.String(length=32), nullable=False),
    sa.Column('dimension', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocated_expenses_period_month'), 'allocated_expenses', ['period_month'], unique=False)
    op.create_index(op.f('ix_allocated_expenses_period_year'), 'allocated_expenses', ['period_year'], unique=False)
    op.create_table('archive_files',
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('uploader', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'period_year', 'period_month', 'category', 'original_name', 'version', name='uq_archive_file_version')
    )
    op.create_index(op.f('ix_archive_files_company'), 'archive_files', ['company'], unique=False)
    op.create_index(op.f('ix_archive_files_period_month'), 'archive_files', ['period_month'], unique=False)
    op.create_index(op.f('ix_archive_files_period_year'), 'archive_files', ['period_year'], unique=False)
    op.create_index(op.f('ix_archive_files_sha256'), 'archive_files', ['sha256'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_id'), 'audit_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_object_type'), 'audit_logs', ['object_type'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('account_no', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=False),
    sa.Column('bank_name', sa.String(length=256), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_no')
    )
    op.create_table('bank_import_batches',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('archive_file_id', sa.BigInteger(), nullable=True),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_import_batches_period_month'), 'bank_import_batches', ['period_month'], unique=False)
    op.create_index(op.f('ix_bank_import_batches_period_year'), 'bank_import_batches', ['period_year'], unique=False)
    op.create_table('bank_receipt_files',
    sa.Column('archive_file_id', sa.BigInteger(), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_receipt_files_archive_file_id'), 'bank_receipt_files', ['archive_file_id'], unique=False)
    op.create_table('bank_transaction_receipt_links',
    sa.Column('txn_id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_file_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_id', 'receipt_file_id', name='uq_txn_receipt')
    )
    op.create_index(op.f('ix_bank_transaction_receipt_links_receipt_file_id'), 'bank_transaction_receipt_links', ['receipt_file_id'], unique=False)
    op.create_index(op.f('ix_bank_transaction_receipt_links_txn_id'), 'bank_transaction_receipt_links', ['txn_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('counterparty_name', sa.String(length=256), nullable=False),
    sa.Column('counterparty_account', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('voucher_no', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('fingerprint', name='uq_bank_txn_fingerprint')
    )
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_counterparty_name'), 'bank_transactions', ['counterparty_name'], unique=False)
    op.create_index(op.f('ix_bank_transactions_import_batch_id'), 'bank_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_txn_date'), 'bank_transactions', ['txn_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_voucher_no'), 'bank_transactions', ['voucher_no'], unique=False)
    op.create_table('closing_versions',
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'version', name='uq_closing_version')
    )
    op.create_index(op.f('ix_closing_versions_period_id'), 'closing_versions', ['period_id'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('purch_order_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('default_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'period_year', 'period_month', 'source', name='uq_cost_sku_period_src')
    )
    op.create_index(op.f('ix_cost_snapshots_sku_id'), 'cost_snapshots', ['sku_id'], unique=False)
    op.create_table('counterparty_mapping_rules',
    sa.Column('match_pattern', sa.String(length=256), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_mapping_rules_match_pattern'), 'counterparty_mapping_rules', ['match_pattern'], unique=False)
    op.create_table('email_delivery_logs',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('to_addrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_addrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_delivery_logs_package_id'), 'email_delivery_logs', ['package_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ref_table', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=False),
    sa.Column('handled_by', sa.String(length=64), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_code'), 'exceptions', ['code'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_exceptions_type'), 'exceptions', ['type'], unique=False)
    op.create_table('external_purchase_order_raw_items',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_title', sa.Text(), nullable=False),
    sa.Column('raw_spec', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_purchase_order_raw_items_po_id'), 'external_purchase_order_raw_items', ['po_id'], unique=False)
    op.create_table('external_purchase_orders',
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('buyer_account', sa.String(length=128), nullable=False),
    sa.Column('supplier_name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=False),
    sa.Column('pay_status', sa.String(length=64), nullable=False),
    sa.Column('ship_status', sa.String(length=64), nullable=False),
    sa.Column('refund_status', sa.String(length=64), nullable=False),
    sa.Column('logistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('purchase_status', sa.String(length=32), nullable=False),
    sa.Column('invoice_status', sa.String(length=32), nullable=False),
    sa.Column('allocated_goods_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('allocated_expense_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('refined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id')
    )
    op.create_index(op.f('ix_external_purchase_orders_invoice_status'), 'external_purchase_orders', ['invoice_status'], unique=False)
    op.create_index(op.f('ix_external_purchase_orders_order_status'), 'external_purchase_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_external_purchase_orders_ordered_at'), 'external_purchase_orders', ['ordered_at'], unique=False)
    op.create_index(op.f('ix_external_purchase_orders_purchase_status'), 'external_purchase_orders', ['purchase_status'], unique=False)
    op.create_index(op.f('ix_external_purchase_orders_supplier_name'), 'external_purchase_orders', ['supplier_name'], unique=False)
    op.create_table('finance_delivery_files',
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('archive_file_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_delivery_files_archive_file_id'), 'finance_delivery_files', ['archive_file_id'], unique=False)
    op.create_index(op.f('ix_finance_delivery_files_package_id'), 'finance_delivery_files', ['package_id'], unique=False)
    op.create_table('finance_delivery_packages',
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('zip_path', sa.Text(), nullable=False),
    sa.Column('zip_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at_src', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_delivery_packages_period_id'), 'finance_delivery_packages', ['period_id'], unique=False)
    op.create_table('inbound_links',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('goodsdoc_no', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_links_goodsdoc_no'), 'inbound_links', ['goodsdoc_no'], unique=False)
    op.create_index(op.f('ix_inbound_links_po_id'), 'inbound_links', ['po_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'mode', name='uq_integration_provider_mode')
    )
    op.create_index(op.f('ix_integration_connections_provider'), 'integration_connections', ['provider'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('key_hint', sa.String(length=128), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_credentials_provider'), 'integration_credentials', ['provider'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_sku_id'), 'inventory_snapshots', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_warehouse_id'), 'inventory_snapshots', ['warehouse_id'], unique=False)
    op.create_table('jackyun_purchase_order_links',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('jackyun_po_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_id', 'jackyun_po_id', name='uq_po_jackyunpo')
    )
    op.create_index(op.f('ix_jackyun_purchase_order_links_jackyun_po_id'), 'jackyun_purchase_order_links', ['jackyun_po_id'], unique=False)
    op.create_index(op.f('ix_jackyun_purchase_order_links_po_id'), 'jackyun_purchase_order_links', ['po_id'], unique=False)
    op.create_table('jackyun_purchase_orders',
    sa.Column('jackyun_purch_id', sa.String(length=64), nullable=False),
    sa.Column('purch_no', sa.String(length=128), nullable=False),
    sa.Column('supplier_name', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jackyun_purch_id')
    )
    op.create_index(op.f('ix_jackyun_purchase_orders_purch_no'), 'jackyun_purchase_orders', ['purch_no'], unique=False)
    op.create_table('monthly_finance_periods',
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('required_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'period_year', 'period_month', name='uq_finance_period')
    )
    op.create_table('opening_adjustments',
    sa.Column('opening_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_adjustments_opening_id'), 'opening_adjustments', ['opening_id'], unique=False)
    op.create_table('opening_balances',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_balances_kind'), 'opening_balances', ['kind'], unique=False)
    op.create_index(op.f('ix_opening_balances_ref'), 'opening_balances', ['ref'], unique=False)
    op.create_table('product_skus',
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('jackyun_sku_id', sa.String(length=64), nullable=False),
    sa.Column('sku_code', sa.String(length=128), nullable=False),
    sa.Column('sku_name', sa.String(length=512), nullable=False),
    sa.Column('barcode', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('default_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jackyun_sku_id'),
    sa.UniqueConstraint('jackyun_sku_id', name='uq_sku_jackyun_id')
    )
    op.create_index(op.f('ix_product_skus_barcode'), 'product_skus', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_skus_product_id'), 'product_skus', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_skus_sku_code'), 'product_skus', ['sku_code'], unique=False)
    op.create_index(op.f('ix_product_skus_sku_name'), 'product_skus', ['sku_name'], unique=False)
    op.create_table('products',
    sa.Column('jackyun_goods_id', sa.String(length=64), nullable=False),
    sa.Column('goods_code', sa.String(length=128), nullable=False),
    sa.Column('goods_name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jackyun_goods_id')
    )
    op.create_index(op.f('ix_products_goods_code'), 'products', ['goods_code'], unique=False)
    op.create_index(op.f('ix_products_goods_name'), 'products', ['goods_name'], unique=False)
    op.create_table('profit_snapshots',
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('dimension', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('goods_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ad_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('logistics_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('other_fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('contribution_profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('data_version', sa.String(length=32), nullable=False),
    sa.Column('cost_missing', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_snapshots_period_month'), 'profit_snapshots', ['period_month'], unique=False)
    op.create_index(op.f('ix_profit_snapshots_period_year'), 'profit_snapshots', ['period_year'], unique=False)
    op.create_table('purchase_allocation_items',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_code', sa.String(length=128), nullable=False),
    sa.Column('goods_name', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_allocation_items_po_id'), 'purchase_allocation_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_allocation_items_sku_code'), 'purchase_allocation_items', ['sku_code'], unique=False)
    op.create_index(op.f('ix_purchase_allocation_items_sku_id'), 'purchase_allocation_items', ['sku_id'], unique=False)
    op.create_table('purchase_extra_expenses',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('expense_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('allocate_method', sa.String(length=32), nullable=False),
    sa.Column('distribute', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_extra_expenses_po_id'), 'purchase_extra_expenses', ['po_id'], unique=False)
    op.create_table('purchase_invoice_links',
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'po_id', name='uq_invoice_po')
    )
    op.create_index(op.f('ix_purchase_invoice_links_invoice_id'), 'purchase_invoice_links', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_links_po_id'), 'purchase_invoice_links', ['po_id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('invoice_no', sa.String(length=128), nullable=False),
    sa.Column('supplier_name', sa.String(length=256), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoices_invoice_no'), 'purchase_invoices', ['invoice_no'], unique=False)
    op.create_table('raw_api_payloads',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_api_payloads_provider'), 'raw_api_payloads', ['provider'], unique=False)
    op.create_index(op.f('ix_raw_api_payloads_request_digest'), 'raw_api_payloads', ['request_digest'], unique=False)
    op.create_table('receivable_snapshots',
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('opening', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('incurred', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('settled', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('closing', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'period_year', 'period_month', name='uq_receivable_period')
    )
    op.create_table('reconciliation_matches',
    sa.Column('txn_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('matched_platform', sa.String(length=64), nullable=False),
    sa.Column('matched_by', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_matches_txn_id'), 'reconciliation_matches', ['txn_id'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sales_channels',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sales_order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_code', sa.String(length=128), nullable=False),
    sa.Column('goods_name', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_order_id'), 'sales_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_order_items_sku_code'), 'sales_order_items', ['sku_code'], unique=False)
    op.create_index(op.f('ix_sales_order_items_sku_id'), 'sales_order_items', ['sku_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('order_no', sa.String(length=128), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=64), nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=False),
    sa.Column('pay_status', sa.String(length=64), nullable=False),
    sa.Column('buyer_note', sa.Text(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_sales_orders_order_status'), 'sales_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_sales_orders_ordered_at'), 'sales_orders', ['ordered_at'], unique=False)
    op.create_index(op.f('ix_sales_orders_platform'), 'sales_orders', ['platform'], unique=False)
    op.create_index(op.f('ix_sales_orders_store_id'), 'sales_orders', ['store_id'], unique=False)
    op.create_table('settlement_records',
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('store_name', sa.String(length=256), nullable=False),
    sa.Column('period_year', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.BigInteger(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_records_period_month'), 'settlement_records', ['period_month'], unique=False)
    op.create_index(op.f('ix_settlement_records_period_year'), 'settlement_records', ['period_year'], unique=False)
    op.create_index(op.f('ix_settlement_records_platform'), 'settlement_records', ['platform'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_no', sa.String(length=128), nullable=False),
    sa.Column('carrier', sa.String(length=128), nullable=False),
    sa.Column('tracking_no', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_no'), 'shipments', ['shipment_no'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_no'), 'shipments', ['tracking_no'], unique=False)
    op.create_table('stores',
    sa.Column('jackyun_store_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jackyun_store_id')
    )
    op.create_index(op.f('ix_stores_platform'), 'stores', ['platform'], unique=False)
    op.create_table('suppliers',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_shop_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('contact', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_external_shop_id'), 'suppliers', ['external_shop_id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'job_type', name='uq_checkpoint_provider_job')
    )
    op.create_table('sync_jobs',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_provider'), 'sync_jobs', ['provider'], unique=False)
    op.create_table('sync_logs',
    sa.Column('sync_job_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_provider'), 'sync_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_sync_logs_sync_job_id'), 'sync_logs', ['sync_job_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouses',
    sa.Column('jackyun_warehouse_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('warehouse_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jackyun_warehouse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sync_logs_sync_job_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_provider'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_sync_jobs_provider'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('sync_checkpoints')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_external_shop_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_stores_platform'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_shipments_tracking_no'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_no'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_settlement_records_platform'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_period_year'), table_name='settlement_records')
    op.drop_index(op.f('ix_settlement_records_period_month'), table_name='settlement_records')
    op.drop_table('settlement_records')
    op.drop_index(op.f('ix_sales_orders_store_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_platform'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_ordered_at'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_status'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_sales_order_items_sku_id'), table_name='sales_order_items')
    op.drop_index(op.f('ix_sales_order_items_sku_code'), table_name='sales_order_items')
    op.drop_index(op.f('ix_sales_order_items_order_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_table('sales_channels')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reconciliation_matches_txn_id'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_table('receivable_snapshots')
    op.drop_index(op.f('ix_raw_api_payloads_request_digest'), table_name='raw_api_payloads')
    op.drop_index(op.f('ix_raw_api_payloads_provider'), table_name='raw_api_payloads')
    op.drop_table('raw_api_payloads')
    op.drop_index(op.f('ix_purchase_invoices_invoice_no'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoice_links_po_id'), table_name='purchase_invoice_links')
    op.drop_index(op.f('ix_purchase_invoice_links_invoice_id'), table_name='purchase_invoice_links')
    op.drop_table('purchase_invoice_links')
    op.drop_index(op.f('ix_purchase_extra_expenses_po_id'), table_name='purchase_extra_expenses')
    op.drop_table('purchase_extra_expenses')
    op.drop_index(op.f('ix_purchase_allocation_items_sku_id'), table_name='purchase_allocation_items')
    op.drop_index(op.f('ix_purchase_allocation_items_sku_code'), table_name='purchase_allocation_items')
    op.drop_index(op.f('ix_purchase_allocation_items_po_id'), table_name='purchase_allocation_items')
    op.drop_table('purchase_allocation_items')
    op.drop_index(op.f('ix_profit_snapshots_period_year'), table_name='profit_snapshots')
    op.drop_index(op.f('ix_profit_snapshots_period_month'), table_name='profit_snapshots')
    op.drop_table('profit_snapshots')
    op.drop_index(op.f('ix_products_goods_name'), table_name='products')
    op.drop_index(op.f('ix_products_goods_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_skus_sku_name'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_sku_code'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_product_id'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_barcode'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index(op.f('ix_opening_balances_ref'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_kind'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_opening_adjustments_opening_id'), table_name='opening_adjustments')
    op.drop_table('opening_adjustments')
    op.drop_table('monthly_finance_periods')
    op.drop_index(op.f('ix_jackyun_purchase_orders_purch_no'), table_name='jackyun_purchase_orders')
    op.drop_table('jackyun_purchase_orders')
    op.drop_index(op.f('ix_jackyun_purchase_order_links_po_id'), table_name='jackyun_purchase_order_links')
    op.drop_index(op.f('ix_jackyun_purchase_order_links_jackyun_po_id'), table_name='jackyun_purchase_order_links')
    op.drop_table('jackyun_purchase_order_links')
    op.drop_index(op.f('ix_inventory_snapshots_warehouse_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_sku_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_integration_credentials_provider'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_integration_connections_provider'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_inbound_links_po_id'), table_name='inbound_links')
    op.drop_index(op.f('ix_inbound_links_goodsdoc_no'), table_name='inbound_links')
    op.drop_table('inbound_links')
    op.drop_index(op.f('ix_finance_delivery_packages_period_id'), table_name='finance_delivery_packages')
    op.drop_table('finance_delivery_packages')
    op.drop_index(op.f('ix_finance_delivery_files_package_id'), table_name='finance_delivery_files')
    op.drop_index(op.f('ix_finance_delivery_files_archive_file_id'), table_name='finance_delivery_files')
    op.drop_table('finance_delivery_files')
    op.drop_index(op.f('ix_external_purchase_orders_supplier_name'), table_name='external_purchase_orders')
    op.drop_index(op.f('ix_external_purchase_orders_purchase_status'), table_name='external_purchase_orders')
    op.drop_index(op.f('ix_external_purchase_orders_ordered_at'), table_name='external_purchase_orders')
    op.drop_index(op.f('ix_external_purchase_orders_order_status'), table_name='external_purchase_orders')
    op.drop_index(op.f('ix_external_purchase_orders_invoice_status'), table_name='external_purchase_orders')
    op.drop_table('external_purchase_orders')
    op.drop_index(op.f('ix_external_purchase_order_raw_items_po_id'), table_name='external_purchase_order_raw_items')
    op.drop_table('external_purchase_order_raw_items')
    op.drop_index(op.f('ix_exceptions_type'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_code'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_email_delivery_logs_package_id'), table_name='email_delivery_logs')
    op.drop_table('email_delivery_logs')
    op.drop_index(op.f('ix_counterparty_mapping_rules_match_pattern'), table_name='counterparty_mapping_rules')
    op.drop_table('counterparty_mapping_rules')
    op.drop_index(op.f('ix_cost_snapshots_sku_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_closing_versions_period_id'), table_name='closing_versions')
    op.drop_table('closing_versions')
    op.drop_index(op.f('ix_bank_transactions_voucher_no'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_txn_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_import_batch_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_counterparty_name'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_bank_transaction_receipt_links_txn_id'), table_name='bank_transaction_receipt_links')
    op.drop_index(op.f('ix_bank_transaction_receipt_links_receipt_file_id'), table_name='bank_transaction_receipt_links')
    op.drop_table('bank_transaction_receipt_links')
    op.drop_index(op.f('ix_bank_receipt_files_archive_file_id'), table_name='bank_receipt_files')
    op.drop_table('bank_receipt_files')
    op.drop_index(op.f('ix_bank_import_batches_period_year'), table_name='bank_import_batches')
    op.drop_index(op.f('ix_bank_import_batches_period_month'), table_name='bank_import_batches')
    op.drop_table('bank_import_batches')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_audit_logs_object_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_object_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_archive_files_sha256'), table_name='archive_files')
    op.drop_index(op.f('ix_archive_files_period_year'), table_name='archive_files')
    op.drop_index(op.f('ix_archive_files_period_month'), table_name='archive_files')
    op.drop_index(op.f('ix_archive_files_company'), table_name='archive_files')
    op.drop_table('archive_files')
    op.drop_index(op.f('ix_allocated_expenses_period_year'), table_name='allocated_expenses')
    op.drop_index(op.f('ix_allocated_expenses_period_month'), table_name='allocated_expenses')
    op.drop_table('allocated_expenses')
    op.drop_index(op.f('ix_aftersales_orders_status'), table_name='aftersales_orders')
    op.drop_index(op.f('ix_aftersales_orders_order_no'), table_name='aftersales_orders')
    op.drop_table('aftersales_orders')
    # ### end Alembic commands ###
